version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "STMLABSDB"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - /volumes/stmlabdb/:/var/lib/postgresql/data
    ports:
      - "5433:5432"